config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root webpage
  root 'application#home'


  # user registration, login and authentication routes:
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  # registration
  get 'register' => 'users#new'
  post 'register' => 'users#create'
  # add user nested routes here!
  resources :users, only: [:show, :edit, :update] do
    #resources :matches
    resources :guides
    # for some unholy reason deleting won't work unless i do this badness
    get '/guides/:id/delete' => 'guides#destroy', as: 'delete_guide'
    
  end
  get '/logout' => 'sessions#destroy'

  resources :maps
  # see line 20
  get '/maps/:id/delete' => 'maps#destroy', as: 'delete_map'
  
  resources :guides, only: [:index, :show]
  
  # creating and updating guides will also not work unless i do this badness
  post '/guides/' => 'guides#create'
  patch '/guides/:id' => 'guides#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guide.rb
class Guide < ApplicationRecord
    # validations
    # title must be present
    validates :title, presence: true
    # minimum guide body length
    validates :body, length: {minimum: 50}
    # should never not be present, but just in case:
    validates :map_id, presence: true

    # scope method
    scope :char_count, -> (num) { where("LENGTH(body) > ?", num) }

    # relationships
    belongs_to :map
    belongs_to :user
end

app/models/map.rb
class Map < ApplicationRecord
    # validations
    validates :name, presence: true, uniqueness: true

    has_many :matches
    has_many :guides
    has_many :users, through: :guides
end

app/models/user.rb
class User < ApplicationRecord
    # allows users to create an account without a password (used for omniauth),
    # create a custom validation later for local accounts!!
    has_secure_password :validations => false
    # switch to regular has_secure_password once omniauth stuff is sorted out
    #has_secure_password


    validates :name, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true

    has_many :guides
    has_many :maps, through: :guides
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def home
        if session[:name].nil?
            render 'home'
        end
    end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
    before_action :require_login, except: [:index, :show]
    before_action :check_if_same_author, except: [:index, :show, :new, :create]

    def index
        @guides = Guide.all
    end

    def new
        @user = User.find(session[:user_id])
    end

    def create
        @guide = Guide.create(guide_params)
        if @guide.valid?
            redirect_to guide_path(@guide)
        else
            flash[:alert] = @guides.errors.full_messages
            redirect_to new_user_guide_path(params[:user_id])
        end
    end

    def show
        @guide = Guide.find(params[:id])
    end

    def edit
        @user = User.find(session[:user_id])
        @guide = Guide.find(params[:id])
    end

    def update
        #byebug
        @guide = Guide.find(params[:id])
        @guide.update(guide_params)

        if @guide.valid?
            redirect_to user_guide_path(@guide.user, @guide)
        else
            flash[:alert] = @guide.errors.full_messages
            redirect_to edit_user_guide_path(@guide.user, @guide)
        end
        
    end

    def destroy
        #byebug
        @guide = Guide.find(params[:id])
        @guide.destroy
        redirect_to guides_path
    end

    private

    def require_login
        return head(:forbidden) unless session.include? :user_id
    end

    def check_if_same_author
        if params[:guide]
            puts "bazinga"
            return head(:forbidden) unless params[:guide][:user_id] == session[:user_id].to_s
        else
            puts "billy bongo"
            return head(:forbidden) unless params[:user_id] == session[:user_id].to_s
        end
        
    end

    def guide_params
        params.require(:guide).permit(:title, :body, :user_id, :map_id)
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
        @maps = Map.all
    end

    def new
    end

    def create
        @map = Map.create(map_params)
        if @map.valid?
            redirect_to map_path(@map)
        else
            flash[:alert] = @map.errors.full_messages
            redirect_to new_map_path
        end
    end

    def show
        @map = Map.find(params[:id])
    end

    def edit
        @map = Map.find(params[:id])
    end

    def update
        @map = Map.find(params[:id])
        @map.update(map_params)
        #byebug
        if @map.valid?
            redirect_to map_path(@map)
        else
            flash[:alert] = @map.errors.full_messages
            redirect_to edit_map_path(@map)
        end
    end

    def destroy
        byebug
        @map = Map.find(params[:id])
        @map.destroy
        redirect_to maps_path
    end

    private

    def map_params
        params.require(:map).permit(:name)
    end
end

app/controllers/sessions_controller.rb
require 'securerandom' # for assigning random passwords to omniauth logins

class SessionsController < ApplicationController
    # used for auth strategies
    skip_before_action :verify_authenticity_token, only: :create

    def new
        if session[:user_id]
            redirect_to root_path
        else
            render 'login'
        end
    end

    def create
        #byebug
        if auth # if logged in using omniauth
            @user = User.find_by(email: auth['info']['email'])
            sessions_helper.check_if_user_exists @user, auth, flash
            session[:user_id] = @user.id
            redirect_to root_path
        else    # if logged in manually
            login_info = params[:user]
            @user = User.find_by(name: login_info[:name])
            #byebug
            if @user && @user.authenticate(login_info[:password])
                session[:user_id] = @user.id
                redirect_to root_path
            else
                flash[:alert] = "Invalid username or password!"
                redirect_to login_path
            end
        end
    end

    def destroy
        session.delete :user_id
        redirect_to root_path
    end

    private

    def sessions_helper
        ApplicationController.helpers
    end

    def auth
        request.env['omniauth.auth']
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create]

    # adding just in case I decide to implement this
    def index
    end

    def new
        if session[:user_id]
            redirect_to root_path
        else
            render 'register'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.omniauth = false
            @user.save
            redirect_to root_path
        else
            flash[:alert] = "That username or email is already in use!"
            redirect_to register_path
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    # once again, adding just in case
    def destroy
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

    def require_login()
        return head(:forbidden) unless session.include? :user_id
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
    def show_guide_link(guide)
        link_to guide.title, guide_path(guide)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def check_if_user_exists(user, auth, flash)
        if user && user.omniauth == false
            flash[:alert] = "A user with your email already exists!"
            redirect_to login_path
        elsif user.nil?
            user = User.new()
            user.name = auth['info']['name']
            user.email = auth['info']['email']
            user.password = SecureRandom.hex
            user.omniauth = true
            user.save
        end
    end
end

app/views/application/home.html.erb
Home page<br>

app/views/guides/_form.html.erb
<% if flash[:alert] %>
    <% flash[:alert].each do |msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %><br>
    <% end %>
<% end %>

<%= form_with model: guide do |f| %>
    <%= f.hidden_field :user_id, value: user.id %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <%= f.label 'Map:'%><br>
    <%= f.collection_select :map_id, Map.all, :id, :name%><br>
    <%= f.label :body%><br>
    <%= f.text_field :body %><br>
    <%= f.submit %>
<% end %>

app/views/guides/edit.html.erb
<%= render partial: 'guides/form', locals: {guide: @guide, user: @user, maps: Map.all}%>

app/views/guides/index.html.erb
<% if session[:user_id]%>
    <%= link_to 'New Guide', new_user_guide_path(User.find(session[:user_id])) %><br>
    <br>
<% end%>

<% @guides.each do |guide| %>
    <%= show_guide_link guide %><br>
<% end %>

app/views/guides/new.html.erb
<%= render partial: 'guides/form', locals: {guide: Guide.new, user: @user, maps: Map.all}%>

app/views/guides/show.html.erb
<%= link_to 'Guide Index', guides_path %><br>
<br>
<%= @guide.title %><br>
By <%= link_to @guide.user.name, user_path(@guide.user) %><br>
<%= @guide.body %><br>
<%= link_to @guide.map.name, map_path(@guide.map) %><br>
<br>
<%= link_to 'Edit Guide', edit_user_guide_path(@guide.user, @guide) %>
<%= link_to 'Delete Guide', user_delete_guide_path(@guide.user, @guide) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValorTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home', root_path %> 
    <%= link_to 'Maps', maps_path %>
    <%= link_to 'Guides', guides_path %>
    <% if session[:user_id] %>
      <%= link_to 'Profile', user_path(User.find(session[:user_id])) %>
      <%= link_to 'Logout', logout_path %>
    <% else %>
      <%= link_to 'Login', login_path %>
      <%= link_to 'Register', register_path %>
    <% end %>
    <br>
    <br>
    <%= yield %>
  </body>
</html>

app/views/maps/_form.html.erb
<% if flash[:alert] %>
    <% flash[:alert].each do |msg| %>
        <%= content_tag :div, msg, class: "alert alert-info" %><br>
    <% end %>
<% end %>

<%= form_with model: map do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.submit %>
<% end %>

app/views/maps/edit.html.erb
<%= render partial: "maps/form", locals: {map: @map}%>

app/views/maps/index.html.erb
<% @maps.each do |map| %>
    <%= link_to map.name, map_path(map) %><br>
<% end %>

app/views/maps/new.html.erb
<%= render partial: "maps/form", locals: {map: Map.new}%>

app/views/maps/show.html.erb
<h1><%= @map.name %></h1>
<%= link_to 'Edit Map', edit_map_path(@map) %>
<%= link_to 'Delete Map', delete_map_path(@map) %>

app/views/users/edit.html.erb
<%= form_with model: @user do |f| %>
    <%= f.label "Username" %><br>
    <%= f.text_field :name %><br>
    <%= f.label :email %><br>
    <%= f.text_field :email%><br>
    <%= f.label :password %><br>
    <%= f.password_field :password%><br>
    <%= f.submit %>
<% end %>

app/views/users/register.html.erb
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>

<%= form_with model: User.new, url: '/register', method: 'post' do |f| %>
    <%= f.label "Username" %><br>
    <%= f.text_field :name %><br>
    <%= f.label :email%><br>
    <%= f.text_field :email %><br>
    <%= f.label :password%><br>
    <%= f.password_field :password %><br>
    <%= f.submit "Register" %>
<% end %>

<!--Maybe use a helper method for these in the future?-->
<%= link_to 'Register with Developer', '/auth/developer' %><br>
<%= link_to 'Register with Google', '/auth/google_oauth2' %><br>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.email %></p>
<%= (link_to 'Edit Account Info', edit_user_path) unless @user.omniauth %><br>
<br>
<%= link_to 'View Guides', user_guides_path(@user) %><br>